eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
      instance:
        hostname: localhost
        
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENTSERVICE/payment/doPayment

  order-service:
    endpoints:
      endpoint:
        uri: http://ORDERSERVICE/order/bookOrder        
