eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
      instance:
        hostname: localhost
        
microservice:
  PAYMENTSERVICE:
    endpoints:
      endpoint:
        uri: http://PAYMENTSERVICE/payment/doPayment

  ORDERNAME:
    endpoints:
      endpoint:
        uri: http://ORDERNAME/order/bookOrder        
